#!/usr/bin/env bash

PORT=5000
DEBUG=''


# process command line arguments
while getopts ':p:dh' OPTION; do
    case "$OPTION" in
        p)
            PORT=${OPTARG}
            ;;
        d)
            DEBUG="--debug-mode"
            ;;
        h)
            echo "run-web -p PORT -d"
            exit 0
            ;;
        ?)
            echo "run-web -p PORT -d"
            exit 0
            ;;
    esac
done
shift "$(($OPTIND -1))"

SCRIPTPATH=$(cd $(dirname $0); pwd -P)
export PYTHONPATH=${SCRIPTPATH}:${PYTHONPATH}
. ${LOGONROOT}/dot.bashrc 

mod_wsgi-express start-server \
                 --port ${PORT} \
                 ${DEBUG} \
                 --reload-on-changes \
                 --document-root www \
                 --directory-index index.html \
                 --entry-point wsgi.py
